import type { ComponentType } from "react";
import {
  Bell,
  BookOpen,
  Briefcase,
  Bus,
  CalendarDays,
  ClipboardCheck,
  CreditCard,
  FileText,
  GraduationCap,
  HeartPulse,
  LayoutDashboard,
  Library,
  MapPin,
  MessageSquare,
  Package,
  School,
  ScrollText,
  Settings,
  Trophy,
  Users,
  FlaskConical,
  UserRound,
} from "lucide-react";

type Icon = typeof LayoutDashboard;
export type NavItem = { to: string; label: string; icon: Icon };
export type NavGroup = { id: string; label: string; items: NavItem[] };

const all: NavGroup[] = [
  { id: "overview", label: "Overview", items: [{ to: "/app/dashboard", label: "Dashboard", icon: LayoutDashboard }] },
  {
    id: "org",
    label: "Organisation",
    items: [
      { to: "/app/branches", label: "Branches", icon: School },
      { to: "/app/users", label: "Users & Roles", icon: Users },
      { to: "/app/academic-years", label: "Academic Years", icon: CalendarDays },
      { to: "/app/settings", label: "Settings", icon: Settings },
      { to: "/app/audit", label: "Audit Logs", icon: ClipboardCheck },
    ],
  },
  {
    id: "admissions",
    label: "Admissions",
    items: [
      { to: "/app/enquiries", label: "Enquiries", icon: MessageSquare },
      { to: "/app/applications", label: "Applications", icon: FileText },
      { to: "/app/entrance-tests", label: "Entrance tests", icon: ScrollText },
      { to: "/app/interviews", label: "Interviews", icon: Users },
      { to: "/app/admissions", label: "Admissions", icon: GraduationCap },
    ],
  },
  {
    id: "people",
    label: "Students",
    items: [
      { to: "/app/students", label: "All Students", icon: Users },
      { to: "/app/promotions", label: "Student Promotion", icon: GraduationCap },
      { to: "/app/transfers", label: "Transfer / TC", icon: FileText },
      { to: "/app/documents", label: "Documents", icon: FileText },
      { to: "/app/guardians", label: "Parents & Guardians", icon: UserRound },
      { to: "/app/children", label: "My children", icon: Users },
    ],
  },
  {
    id: "staff",
    label: "Staff",
    items: [
      { to: "/app/teachers", label: "Teachers", icon: GraduationCap },
      { to: "/app/staff", label: "Non-Teaching Staff", icon: Briefcase },
      { to: "/app/hr", label: "HR & Payroll", icon: Briefcase },
    ],
  },
  {
    id: "academics",
    label: "Academics",
    items: [
      { to: "/app/classes", label: "Classes & sections", icon: School },
      { to: "/app/subjects", label: "Subjects", icon: BookOpen },
      { to: "/app/timetable", label: "Timetable", icon: CalendarDays },
      { to: "/app/homework", label: "Homework", icon: BookOpen },
      { to: "/app/exams", label: "Exams & results", icon: ScrollText },
      { to: "/app/marks", label: "Marks", icon: ScrollText },
      { to: "/app/results", label: "Results", icon: ScrollText },
      { to: "/app/report-cards", label: "Report cards", icon: ScrollText },
      { to: "/app/study-materials", label: "Study materials", icon: BookOpen },
    ],
  },
  {
    id: "attendance",
    label: "Attendance",
    items: [
      { to: "/app/attendance", label: "Student attendance", icon: ClipboardCheck },
      { to: "/app/staff-attendance", label: "Staff attendance", icon: ClipboardCheck },
      { to: "/app/attendance-reports", label: "Attendance reports", icon: ScrollText },
    ],
  },
  {
    id: "finance",
    label: "Finance",
    items: [
      { to: "/app/fees", label: "Fee Structures", icon: CreditCard },
      { to: "/app/invoices", label: "Student Fees", icon: CreditCard },
      { to: "/app/payments", label: "Payments", icon: CreditCard },
      { to: "/app/receipts", label: "Receipts", icon: ScrollText },
      { to: "/app/pending-fees", label: "Pending fees", icon: CreditCard },
    ],
  },
  {
    id: "comms",
    label: "Communication",
    items: [
      { to: "/app/notices", label: "Notices", icon: Bell },
      { to: "/app/notifications", label: "Notifications", icon: Bell },
      { to: "/app/complaints", label: "Complaints", icon: MessageSquare },
      { to: "/app/communication", label: "Teacher communication", icon: MessageSquare },
    ],
  },
  {
    id: "leave",
    label: "Leave",
    items: [
      { to: "/app/leave", label: "Leave requests", icon: CalendarDays },
      { to: "/app/leave-approvals", label: "Leave approvals", icon: ClipboardCheck },
    ],
  },
  {
    id: "campus",
    label: "Campus",
    items: [
      { to: "/app/transport", label: "Transport", icon: Bus },
      { to: "/app/bus-tracking", label: "Bus Tracking", icon: MapPin },
      { to: "/app/library", label: "Library", icon: Library },
      { to: "/app/inventory", label: "Inventory", icon: Package },
      { to: "/app/events", label: "Events", icon: CalendarDays },
      { to: "/app/hostel", label: "Hostel", icon: School },
      { to: "/app/canteen", label: "Canteen", icon: Package },
      { to: "/app/health", label: "Health", icon: HeartPulse },
      { to: "/app/discipline", label: "Discipline", icon: ClipboardCheck },
      { to: "/app/sports", label: "Sports", icon: Trophy },
      { to: "/app/labs", label: "Lab management", icon: FlaskConical },
      { to: "/app/ptm", label: "PTM", icon: Users },
      { to: "/app/alumni", label: "Alumni", icon: GraduationCap },
    ],
  },
  {
    id: "insights",
    label: "Insights",
    items: [
      { to: "/app/reports", label: "Reports", icon: ScrollText },
      { to: "/app/analytics", label: "Analytics", icon: ScrollText },
    ],
  },
];

const extraAdmin = [
  "/app/enquiries",
  "/app/applications",
  "/app/entrance-tests",
  "/app/interviews",
  "/app/admissions",
  "/app/promotions",
  "/app/transfers",
  "/app/documents",
  "/app/teachers",
  "/app/events",
  "/app/inventory",
  "/app/hr",
  "/app/health",
  "/app/discipline",
  "/app/sports",
  "/app/labs",
  "/app/ptm",
  "/app/alumni",
  "/app/hostel",
  "/app/canteen",
];

const allowByRole: Record<string, string[]> = {
  SUPER_ADMIN: Array.from(new Set(all.flatMap((g) => g.items.map((i) => i.to)))).filter((to) => to !== "/app/children"),
  BRANCH_ADMIN: [
    "/app/dashboard",
    "/app/students",
    "/app/guardians",
    "/app/teachers",
    "/app/staff",
    "/app/hr",
    "/app/academic-years",
    "/app/classes",
    "/app/subjects",
    "/app/timetable",
    "/app/homework",
    "/app/exams",
    "/app/marks",
    "/app/results",
    "/app/report-cards",
    "/app/attendance",
    "/app/staff-attendance",
    "/app/fees",
    "/app/invoices",
    "/app/payments",
    "/app/library",
    "/app/bus-tracking",
    "/app/transport",
    "/app/notices",
    "/app/complaints",
    "/app/communication",
    "/app/leave",
    "/app/leave-approvals",
    "/app/reports",
    "/app/audit",
    "/app/notifications",
    "/app/settings",
    "/app/events",
    "/app/admissions",
    "/app/enquiries",
    "/app/documents",
    "/app/health",
    "/app/discipline",
    "/app/ptm",
  ],
  PRINCIPAL: [
    "/app/dashboard",
    "/app/students",
    "/app/guardians",
    "/app/teachers",
    "/app/staff",
    "/app/classes",
    "/app/subjects",
    "/app/timetable",
    "/app/homework",
    "/app/exams",
    "/app/results",
    "/app/attendance",
    "/app/fees",
    "/app/notices",
    "/app/complaints",
    "/app/leave",
    "/app/leave-approvals",
    "/app/reports",
    "/app/notifications",
    "/app/settings",
    "/app/events",
    "/app/ptm",
    "/app/discipline",
  ],
  TEACHER: [
    "/app/dashboard",
    "/app/classes",
    "/app/students",
    "/app/timetable",
    "/app/attendance",
    "/app/homework",
    "/app/exams",
    "/app/marks",
    "/app/results",
    "/app/leave",
    "/app/notices",
    "/app/notifications",
    "/app/settings",
    "/app/ptm",
    "/app/study-materials",
  ],
  ACCOUNTANT: [
    "/app/dashboard",
    "/app/fees",
    "/app/invoices",
    "/app/payments",
    "/app/receipts",
    "/app/pending-fees",
    "/app/reports",
    "/app/notifications",
    "/app/settings",
  ],
  PARENT: [
    "/app/dashboard",
    "/app/children",
    "/app/timetable",
    "/app/attendance",
    "/app/homework",
    "/app/exams",
    "/app/results",
    "/app/report-cards",
    "/app/marks",
    "/app/study-materials",
    "/app/fees",
    "/app/invoices",
    "/app/receipts",
    "/app/bus-tracking",
    "/app/notices",
    "/app/notifications",
    "/app/complaints",
    "/app/communication",
    "/app/leave",
    "/app/library",
    "/app/events",
    "/app/settings",
  ],
  STUDENT: [
    "/app/dashboard",
    "/app/timetable",
    "/app/attendance",
    "/app/homework",
    "/app/exams",
    "/app/results",
    "/app/report-cards",
    "/app/marks",
    "/app/study-materials",
    "/app/library",
    "/app/notices",
    "/app/notifications",
    "/app/leave",
    "/app/bus-tracking",
    "/app/events",
    "/app/settings",
  ],
};

export function navForRole(role?: string | null): NavGroup[] {
  const allow = new Set(allowByRole[role ?? "STUDENT"] ?? allowByRole.STUDENT);
  return all
    .map((g) => {
      const seen = new Set<string>();
      const items = g.items.filter((i) => {
        if (!allow.has(i.to)) return false;
        if (seen.has(i.to)) return false;
        seen.add(i.to);
        return true;
      });
      return { ...g, items };
    })
    .filter((g) => g.items.length > 0);
}

export type { ComponentType };
export { extraAdmin };
